web:
    build: ./web
    ports:
        - "5000:80"
    volumes:
        - ./web/laravel:/srv/www/code
    links:
        - datamysql
datamysql:
    image: mysql:5.6
    volumes:
        - /tmp/data/mysql:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: admin-password
        MYSQL_DATABASE: dev-db
        MYSQL_USER: dev-user
        MYSQL_PASSWORD: dev-pw
haskell:
    build: ./haskell
    ports:
        - "5001:3000"
    volumes:
        - ./haskell:/code
    command: make run-in-docker
