web:
    build: ./web
    command: php -S 0.0.0.0:5000 app.php
    ports:
        - "5000:5000"
    volumes:
        - ./web:/var/www/html
    links:
        - datamysql
datamysql:
    image: mysql:5.6
    volumes:
        - /tmp/data/mysql:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: admin-password
        MYSQL_DATABASE: dev-db
        MYSQL_USER: dev-user
        MYSQL_PASSWORD: dev-pw
